[default]
### Providers
EXTENSIONS = [
    "bazar.bootstrap.database:init_app",
    "bazar.bootstrap.configuration:init_app",
    "bazar.app.Console.commands:init_app",
    "bazar.app.Http.Routes.api:init_app",
    "bazar.app.Http.Routes.web:init_app"
]

### For development environment
[development]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true

### For production environment
[production]
TEMPLATES_AUTO_RELOAD = false
DEBUG = false
DEBUG_TOOLBAR_ENABLED = false
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = false